// Gzips the Vite build (dist/) into a C header so the firmware serves the editor from flash.
// Usage: npm run build:device   (type check + vite build + this script)
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { extname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = join(root, 'dist');
const out = join(root, '..', 'firmware', 'src', 'net', 'web_assets.h');
const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript',
  '.css': 'text/css',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.json': 'application/json',
};

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
})(dist);

let src = '// Generated by web/scripts/embed.mjs from web/dist. Do not edit.\n#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n';
src += 'struct WebAsset {\n  const char* path;\n  const char* type;\n  const uint8_t* data;\n  size_t len;\n  bool immutable;\n};\n\n';
const entries = [];
let total = 0;
files.sort().forEach((file, i) => {
  const rel = '/' + relative(dist, file).split(sep).join('/');
  const gz = gzipSync(readFileSync(file), { level: 9 });
  total += gz.length;
  const sym = `kAsset${i}`;
  const rows = [];
  for (let k = 0; k < gz.length; k += 24) {
    rows.push('  ' + [...gz.subarray(k, k + 24)].map((b) => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
  }
  src += `// ${rel} (${gz.length} bytes gzipped)\nstatic const uint8_t ${sym}[] = {\n${rows.join('\n')}\n};\n\n`;
  const type = TYPES[extname(file)] ?? 'application/octet-stream';
  const hashed = rel.startsWith('/assets/'); // Vite puts content hashes in these names
  entries.push(`  {"${rel}", "${type}", ${sym}, sizeof(${sym}), ${hashed}},`);
  if (rel === '/index.html') entries.push(`  {"/", "${type}", ${sym}, sizeof(${sym}), false},`);
});
src += `static const WebAsset kWebAssets[] = {\n${entries.join('\n')}\n};\n`;
writeFileSync(out, src);
console.log(`embedded ${files.length} files, ${(total / 1024).toFixed(1)} KB gzipped -> ${relative(root, out)}`);
